name: Build Signed APK

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build web app
        run: npm run build

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/release.jks

      - name: Create keystore.properties
        run: |
          cat > android/keystore.properties <<EOF
          storeFile=app/release.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Grant execute permission
        run: chmod +x android/gradlew

      - name: Build Release APK
        working-directory: android
        run: ./gradlew clean assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShareKitchenHeart-release
          path: android/app/build/outputs/apk/release/app-release.apk
